{
  "_from": "extendo-error@^1.0.1",
  "_id": "extendo-error@1.0.1",
  "_inBundle": false,
  "_integrity": "sha1-MDJeDPbC+l+RAj0hAO0CGCbmMX0=",
  "_location": "/extendo-error",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "extendo-error@^1.0.1",
    "name": "extendo-error",
    "escapedName": "extendo-error",
    "rawSpec": "^1.0.1",
    "saveSpec": null,
    "fetchSpec": "^1.0.1"
  },
  "_requiredBy": [
    "/alsatian"
  ],
  "_resolved": "https://registry.npmjs.org/extendo-error/-/extendo-error-1.0.1.tgz",
  "_shasum": "30325e0cf6c2fa5f91023d2100ed021826e6317d",
  "_spec": "extendo-error@^1.0.1",
  "_where": "/Users/pranavputta/GitHub/linalg_lang/node_modules/alsatian",
  "author": {
    "name": "James Richford"
  },
  "bugs": {
    "url": "https://github.com/jamesrichford/extendo-error/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "Safely and simply extend native Error with prototype chaining support",
  "devDependencies": {
    "alsatian": "^1.0.0-beta.4",
    "typescript": "^2.1.4"
  },
  "homepage": "https://github.com/jamesrichford/extendo-error#readme",
  "keywords": [
    "extendo",
    "error",
    "extendable",
    "typescript",
    "prototype",
    "chaining",
    "extend error",
    "instanceof"
  ],
  "license": "MIT",
  "main": "src/extendo-error.js",
  "name": "extendo-error",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jamesrichford/extendo-error.git"
  },
  "scripts": {
    "build": "tsc",
    "prepublish": "npm test",
    "pretest": "npm run build",
    "test": "alsatian \"**/*.spec.js\""
  },
  "typings": "src/extendo-error.d.ts",
  "version": "1.0.1"
}
